package com.anterka.closeauthbackend.admin.web;

import com.anterka.closeauthbackend.admin.security.RequiresTenantAccess;
import com.anterka.closeauthbackend.client.dto.ClientCountView;
import com.anterka.closeauthbackend.client.dto.ClientCreatedView;
import com.anterka.closeauthbackend.client.dto.ClientSecretView;
import com.anterka.closeauthbackend.client.dto.ClientView;
import com.anterka.closeauthbackend.client.dto.RegisterClientCommand;
import com.anterka.closeauthbackend.client.service.ClientRegistrationService;
import com.anterka.closeauthbackend.common.security.TenantContext;
import com.anterka.closeauthbackend.common.web.PageView;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.oauth2.server.authorization.client.RegisteredClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.UUID;

/**
 * Tenant-scoped client registration (§7.8). {@link RequiresTenantAccess} gate. Wraps {@link ClientRegistrationService}
 * (3c-i/4a); {@code POST} also triggers the 1:1 resource-server auto-create.
 *
 * <p><b>Secret handling (UI-3c):</b> the secret is generated by the backend, never accepted from the caller — see
 * {@code ClientSecretGenerator}'s javadoc. The create response ({@link ClientCreatedView}) and the regenerate
 * response ({@link ClientSecretView}) are the ONLY two places a client secret ever appears — each returned once;
 * only the hash is stored; {@code GET} never returns it.
 *
 * <p><b>FE-4.10: the list gap flagged in STAGE_7B_REPORT.md is now closed.</b> {@code GET} (no path) lists a
 * tenant's clients via {@code TenantAwareRegisteredClientRepository.findByTenantId}, hand-built JDBC reusing SAS's
 * own row mapper (see its javadoc) — the same pattern {@code save()} already used for the INSERT side. Update /
 * delete of clients are still NOT implemented — SAS's {@code RegisteredClientRepository} exposes no tenant-scoped
 * delete, and there is no update use case yet either (flagged, not silently built).
 *
 * <h2>HTTP contract</h2>
 * {@code GET /v1/tenants/{tenantId}/clients} (paged list, no secrets) ·
 * {@code POST /v1/tenants/{tenantId}/clients} (create, 201, secret once — confidential clients only) ·
 * {@code GET .../clients/{clientId}} (no secret) ·
 * {@code POST .../clients/{clientId}/client-secret} (regenerate, 200, new secret once; 409 for a public client).
 */
@RestController
@RequiredArgsConstructor
@RequiresTenantAccess
@RequestMapping("/v1/tenants/{tenantId}/clients")
public class TenantClientController {

    private final ClientRegistrationService clientRegistrationService;

    /**
     * FE-4.10: closes the list gap this class's javadoc has flagged since Stage 7b — declared ahead of
     * {@code /count} and {@code /{clientId}} for readability; Spring matches the more specific literal segments
     * regardless of declaration order.
     */
    @GetMapping
    public PageView<ClientView> list(@PathVariable String tenantId,
                                     @RequestParam(defaultValue = "0") int page,
                                     @RequestParam(defaultValue = "20") int size) {
        return PageView.of(clientRegistrationService.listClients(ctx(tenantId)), page, size);
    }

    @PostMapping
    public ResponseEntity<ClientCreatedView> create(@PathVariable String tenantId,
                                                    @Valid @RequestBody RegisterClientCommand command) {
        ClientCreatedView created = clientRegistrationService.registerClient(ctx(tenantId), command);
        return ResponseEntity.status(HttpStatus.CREATED).body(created);
    }

    /**
     * FE-4d: the console overview's Clients count tile — predates {@link #list}, kept as the cheaper query for
     * that one tile. Declared ahead of {@code /{clientId}} for readability; Spring's request mapping prefers this
     * literal segment over the variable one regardless of order.
     */
    @GetMapping("/count")
    public ClientCountView count(@PathVariable String tenantId) {
        return new ClientCountView(clientRegistrationService.countClients(ctx(tenantId)));
    }

    @GetMapping("/{clientId}")
    public ClientView get(@PathVariable String tenantId, @PathVariable String clientId) {
        RegisteredClient client = clientRegistrationService.loadClientOrThrow(ctx(tenantId), clientId);
        return ClientView.from(client); // no secret
    }

    @PostMapping("/{clientId}/client-secret")
    public ClientSecretView regenerateSecret(@PathVariable String tenantId, @PathVariable String clientId) {
        return clientRegistrationService.regenerateClientSecret(ctx(tenantId), clientId);
    }

    private TenantContext ctx(String tenantId) {
        return TenantContext.of(UUID.fromString(tenantId));
    }
}
