package com.anterka.closeauthbackend.admin.web;

import com.anterka.closeauthbackend.admin.security.RequiresTenantAccess;
import com.anterka.closeauthbackend.client.dto.ClientCreatedView;
import com.anterka.closeauthbackend.client.dto.ClientSecretView;
import com.anterka.closeauthbackend.client.dto.ClientView;
import com.anterka.closeauthbackend.client.dto.RegisterClientCommand;
import com.anterka.closeauthbackend.client.service.ClientRegistrationService;
import com.anterka.closeauthbackend.common.security.TenantContext;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.oauth2.server.authorization.client.RegisteredClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.UUID;

/**
 * Tenant-scoped client registration (§7.8). {@link RequiresTenantAccess} gate. Wraps {@link ClientRegistrationService}
 * (3c-i/4a); {@code POST} also triggers the 1:1 resource-server auto-create.
 *
 * <p><b>Secret handling (UI-3c):</b> the secret is generated by the backend, never accepted from the caller — see
 * {@code ClientSecretGenerator}'s javadoc. The create response ({@link ClientCreatedView}) and the regenerate
 * response ({@link ClientSecretView}) are the ONLY two places a client secret ever appears — each returned once;
 * only the hash is stored; {@code GET} never returns it.
 *
 * <p><b>Flagged gap (STAGE_7B_REPORT.md):</b> list / update / delete of clients are NOT implemented — SAS's
 * {@code RegisteredClientRepository} exposes no tenant-scoped list or delete, so those need custom JDBC over the
 * SAS-managed {@code oauth2_registered_client} table (significant new logic — flagged, not silently built).
 *
 * <h2>HTTP contract</h2>
 * {@code POST /v1/tenants/{tenantId}/clients} (create, 201, secret once — confidential clients only) ·
 * {@code GET .../clients/{clientId}} (no secret) ·
 * {@code POST .../clients/{clientId}/client-secret} (regenerate, 200, new secret once; 409 for a public client).
 */
@RestController
@RequiredArgsConstructor
@RequiresTenantAccess
@RequestMapping("/v1/tenants/{tenantId}/clients")
public class TenantClientController {

    private final ClientRegistrationService clientRegistrationService;

    @PostMapping
    public ResponseEntity<ClientCreatedView> create(@PathVariable String tenantId,
                                                    @Valid @RequestBody RegisterClientCommand command) {
        ClientCreatedView created = clientRegistrationService.registerClient(ctx(tenantId), command);
        return ResponseEntity.status(HttpStatus.CREATED).body(created);
    }

    @GetMapping("/{clientId}")
    public ClientView get(@PathVariable String tenantId, @PathVariable String clientId) {
        RegisteredClient client = clientRegistrationService.loadClientOrThrow(ctx(tenantId), clientId);
        return ClientView.from(client); // no secret
    }

    @PostMapping("/{clientId}/client-secret")
    public ClientSecretView regenerateSecret(@PathVariable String tenantId, @PathVariable String clientId) {
        return clientRegistrationService.regenerateClientSecret(ctx(tenantId), clientId);
    }

    private TenantContext ctx(String tenantId) {
        return TenantContext.of(UUID.fromString(tenantId));
    }
}
